version: "2"
services:
    app:
        build: .
        links:
            - db
        ports:
            - "80:80"
    db:
        image: mysql:8.0
        ports:
            - "3000:3306"
        environment:
            MYSQL_DATABASE: database0
            MYSQL_ROOT_PASSWORD: 199856
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro
